version: '3'
services:
  api:
    build: ./pygrays-api
    ports:
      - "8000:8000"
    restart: on-failure
  web:
    build: ./pygrays-web
    ports:
      - "80:80"
      - "8080:80"
    restart: on-failure